### ISSUE TITLE
Getting issue in Installing

### ISSUE THREAD

**Issue by vishal-iitr2003** [irshadbhat/indic-tokenizer#1]
I am trying to install on windows 10 using python 3.6.2 and getting below error.

Installed c:\python_prctise\indic-tokenizer\.eggs\pbr-2.0.0-py3.6.egg
ERROR:root:Error parsing
Traceback (most recent call last):
  File "c:\python_prctise\indic-tokenizer\.eggs\pbr-2.0.0-py3.6.egg\pbr\core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "c:\python_prctise\indic-tokenizer\.eggs\pbr-2.0.0-py3.6.egg\pbr\util.py", line 251, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "c:\python_prctise\indic-tokenizer\.eggs\pbr-2.0.0-py3.6.egg\pbr\util.py", line 315, in setup_cfg_to_setup_kwargs
    value += description_file.read().strip() + '\n\n'
  File "C:\python_3.6.2\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1073: character maps to <undefined>
error in setup command: Error parsing C:\python_prctise\indic-tokenizer\setup.cfg: UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1073: character maps to <undefined>

**Comment by irshadbhat** [comment]
Hi Vishal,

I installed it on windows 10 with Python3.6 and it worked fine. Can you show me the installation command you used.

**Comment by vishal-iitr2003** [comment]
Tx Irshad.
There was some issue with encoding in setup related file inside .eggs folder. Fixed it locally to install.
Would love to connect with you and discuss few stuffs. Can I have your personal mail id.

**Comment by irshadbhat** [comment]
Nice, you got the issue solved. I am closing the issue then.

You can contact me on bhatirshad127@gmail.com
